import { Hono } from "hono";
import type { HealthResponse } from "@tasklog/shared";
import { createAuth } from "./auth";
import type { AppEnv } from "./types";
import { requireAuth } from "./middleware/auth";
import { workspacesRoute } from "./routes/workspaces";
import { issuesRoute } from "./routes/issues";

// `Env` is generated by `wrangler types` into worker-configuration.d.ts and
// augmented with secrets in env.d.ts.
const app = new Hono<AppEnv>();

// Better Auth handles all /api/auth/* routes (sign-in, callback, session, ...).
app.on(["GET", "POST"], "/api/auth/*", (c) => {
  const auth = createAuth(c.env);
  return auth.handler(c.req.raw);
});

app.get("/api/health", async (c) => {
  let db: HealthResponse["db"] = "ok";
  try {
    await c.env.DB.prepare("SELECT 1").first();
  } catch {
    db = "error";
  }

  const body: HealthResponse = {
    status: "ok",
    db,
    time: new Date().toISOString(),
  };
  return c.json({ data: body });
});

app.route("/api/workspaces", workspacesRoute);

// Project-scoped resources: /api/projects/:projectId/issues
const projectsApi = new Hono<AppEnv>();
projectsApi.use("*", requireAuth);
projectsApi.route("/:projectId/issues", issuesRoute);
app.route("/api/projects", projectsApi);

// Unknown /api routes -> stable JSON 404 (matches the API error envelope).
app.all("/api/*", (c) =>
  c.json({ error: { code: "NOT_FOUND", message: "Not found" } }, 404),
);

export default app;
