import { Hono } from "hono";
import type { HealthResponse } from "@tasklog/shared";

// `Env` is generated by `wrangler types` into worker-configuration.d.ts.
const app = new Hono<{ Bindings: Env }>();

app.get("/api/health", async (c) => {
  let db: HealthResponse["db"] = "ok";
  try {
    await c.env.DB.prepare("SELECT 1").first();
  } catch {
    db = "error";
  }

  const body: HealthResponse = {
    status: "ok",
    db,
    time: new Date().toISOString(),
  };
  return c.json({ data: body });
});

// Unknown /api routes -> stable JSON 404 (matches the API error envelope).
app.all("/api/*", (c) =>
  c.json(
    { error: { code: "NOT_FOUND", message: "Not found" } },
    404,
  ),
);

export default app;
